/**
 * Scenario 7.3: Generated Read Skill
 *
 * Tests that the generated read skill queries state with optional field filtering:
 * - Read skill is invocable as `/test-state.read`
 * - Without arguments, returns all fields
 * - With field argument, returns only that field
 * - Output is in a parseable format (JSON or text)
 *
 * Prerequisites: State skills from 7.1 must be generated
 */
import { Command, Markdown, XmlBlock } from '../../jsx.js';

export default function GeneratedReadSkillTest() {
  return (
    <Command
      name="generated-read-skill-test"
      description="Test the generated read skill for state queries"
    >
      <XmlBlock name="objective">
        Test the generated read skill from State component (scenario 7.1).
        Verify it can read entire state and specific fields.
      </XmlBlock>

      <h2>Prerequisites</h2>
      <Markdown>
        This test requires the state skills generated by scenario 7.1.
        Ensure `/test-state.init` has been run to create the state table.
      </Markdown>

      <h2>Test Setup</h2>
      <Markdown>
        First, initialize the state and populate it with test data.

        1. Run `/test-state.init` if not already done
        2. Set up known test values using `/test-state.write`
      </Markdown>

      <XmlBlock name="setup-instructions">
        Execute these commands to set up test data:

        ```bash
        # Initialize state (if not already done)
        /test-state.init

        # Set known test values
        /test-state.write --field counter --value 100
        /test-state.write --field status --value active
        /test-state.write --field description --value "Test description for read skill"
        ```
      </XmlBlock>

      <h2>Test 1: Read Entire State (No Arguments)</h2>
      <Markdown>
        Invoke the read skill without any field argument.
        It should return all fields as a JSON object.
      </Markdown>

      <XmlBlock name="test-1">
        Execute: `/test-state.read`

        Expected behavior:
        - Returns ALL fields (counter, lastUpdated, status, description)
        - Output is valid JSON
        - All values match what was written in setup

        Report what you receive.
      </XmlBlock>

      <h2>Test 2: Read Specific Field - counter</h2>
      <Markdown>
        Invoke the read skill with a field argument to get a single field.
      </Markdown>

      <XmlBlock name="test-2">
        Execute: `/test-state.read --field counter`

        Expected behavior:
        - Returns ONLY the counter field value
        - Value should be 100 (from setup)
        - Not the entire state object

        Report the returned value.
      </XmlBlock>

      <h2>Test 3: Read Specific Field - status</h2>
      <Markdown>
        Read another specific field to confirm field filtering works consistently.
      </Markdown>

      <XmlBlock name="test-3">
        Execute: `/test-state.read --field status`

        Expected behavior:
        - Returns ONLY the status field value
        - Value should be "active" (from setup)

        Report the returned value.
      </XmlBlock>

      <h2>Test 4: Read Specific Field - description</h2>
      <Markdown>
        Read the description field which contains a longer string value.
      </Markdown>

      <XmlBlock name="test-4">
        Execute: `/test-state.read --field description`

        Expected behavior:
        - Returns ONLY the description field value
        - Value should be "Test description for read skill"

        Report the returned value.
      </XmlBlock>

      <h2>Test 5: Read Specific Field - lastUpdated</h2>
      <Markdown>
        Read the timestamp field to verify datetime handling.
      </Markdown>

      <XmlBlock name="test-5">
        Execute: `/test-state.read --field lastUpdated`

        Expected behavior:
        - Returns ONLY the lastUpdated field value
        - Value should be a valid datetime string

        Report the returned value.
      </XmlBlock>

      <XmlBlock name="validation-output">
        After completing all tests, report results in this YAML format:

        ```yaml
        scenario: 7.3-generated-read-skill
        status: [SUCCESS or FAILURE]
        tests:
          read_entire_state:
            passed: [true/false]
            returned_all_fields: [true/false]
            is_valid_json: [true/false]
          read_field_counter:
            passed: [true/false]
            returned_value: [value]
            expected_value: 100
          read_field_status:
            passed: [true/false]
            returned_value: [value]
            expected_value: "active"
          read_field_description:
            passed: [true/false]
            returned_value: [value]
            expected_value: "Test description for read skill"
          read_field_lastUpdated:
            passed: [true/false]
            is_valid_datetime: [true/false]
        success_criteria:
          read_skill_invocable: [PASSED/FAILED]
          entire_state_read: [PASSED/FAILED]
          field_filtering_works: [PASSED/FAILED]
          output_parseable: [PASSED/FAILED]
        ```
      </XmlBlock>
    </Command>
  );
}
