/**
 * Scenario 9.3: Agent B (Second in Sequential Chain)
 *
 * Second agent in the multi-agent sequential workflow.
 * Receives Agent A's output, transforms it, and produces output for Agent C.
 *
 * Run: node dist/cli/index.js build src/app/scenarios/9.3-agent-b.tsx
 * Output: .claude/agents/9.3-agent-b.md
 */

import { Agent, BaseOutput } from '../../jsx.js';
import type { AgentAOutput } from './9.3-agent-a.js';

/**
 * Input contract for Agent B
 * Matches Agent A's output
 */
export interface AgentBInput extends Omit<AgentAOutput, 'status' | 'message'> {
  /** Processed seed from Agent A */
  processedSeed: string;
  /** Chain ID from Agent A */
  chainId: string;
  /** Step number from Agent A */
  step: number;
  /** Timestamp from Agent A */
  timestampA: string;
}

/**
 * Output contract for Agent B
 * This output becomes Agent C's input
 */
export interface AgentBOutput extends BaseOutput {
  /** Further processed value */
  transformedValue: string;
  /** Chain ID (preserved from A) */
  chainId: string;
  /** Step number (incremented) */
  step: number;
  /** Original A timestamp (preserved) */
  timestampA: string;
  /** Timestamp when B completed */
  timestampB: string;
  /** Confirmation that A's data was received */
  receivedFromA: boolean;
}

export default function AgentB() {
  return (
    <Agent<AgentBInput, AgentBOutput>
      name="9.3-agent-b"
      description="Second agent in sequential chain. Receives Agent A's output and transforms it for Agent C."
    >
      <h1>Agent B - Chain Transformer</h1>

      <p>
        You are Agent B, the second agent in a 3-agent sequential workflow chain.
        Your role is to receive Agent A's output, transform it, and produce output
        that Agent C will consume.
      </p>

      <h2>Your Input</h2>

      <p>
        You will receive Agent A's output fields in your input:
      </p>

      <ul>
        <li>processedSeed: The seed value processed by Agent A</li>
        <li>chainId: The chain ID generated by Agent A</li>
        <li>step: Should be 1 (Agent A's step number)</li>
        <li>timestampA: When Agent A completed</li>
      </ul>

      <h2>Required Actions</h2>

      <ol>
        <li>Acknowledge you are running as "9.3-agent-b"</li>
        <li>Verify you received Agent A's output (check all fields present)</li>
        <li>Transform the processedSeed by prepending "B-transformed-"</li>
        <li>Preserve the chainId from Agent A</li>
        <li>Increment step to 2</li>
        <li>Preserve timestampA</li>
        <li>Record your completion timestamp as timestampB</li>
        <li>Return structured YAML with all required fields</li>
      </ol>

      <h2>Response Format</h2>

      <p>IMPORTANT: End your response with this exact YAML structure:</p>

      <pre><code className="language-yaml">{`status: SUCCESS
transformedValue: B-transformed-[processedSeed value from input]
chainId: [same chainId from input]
step: 2
timestampA: [same timestampA from input]
timestampB: [current ISO timestamp]
receivedFromA: true
message: Agent B completed - data transformed`}</code></pre>

      <h2>Important</h2>

      <p>
        Your output will be passed to Agent C. All fields are REQUIRED.
        You MUST preserve chainId and timestampA from Agent A's output.
        This validates the sequential data flow works correctly.
      </p>
    </Agent>
  );
}
