/**
 * Runtime Template Generator
 *
 * Generates the V3 runtime.js template structure.
 * Used by both generateRuntime and mergeRuntimeResults.
 */

// ============================================================================
// Types
// ============================================================================

/**
 * Options for generating runtime content
 */
export interface RuntimeTemplateOptions {
  /** Function names in registry order */
  functionNames: string[];
  /** Function bodies (must match functionNames order) */
  functionBodies: string[];
  /** Import statements to include */
  imports: string[];
  /** Constant definitions (const NAME = value;) */
  constants: string[];
}

// ============================================================================
// Template Generator
// ============================================================================

/**
 * Generate the runtime.js file content
 *
 * Creates a Node.js executable with:
 * - Dynamic imports (ESM compatible)
 * - Extracted constants
 * - Extracted functions
 * - Function registry
 * - CLI entry point
 *
 * @param options - Template configuration
 * @returns Complete runtime.js file content
 */
export function generateRuntimeContent(options: RuntimeTemplateOptions): string {
  const { functionNames, functionBodies, imports, constants } = options;

  // Generate imports section
  const importsSection = imports.length > 0
    ? `  // Imports (dynamic for ESM compatibility)
${imports.map(i => '  ' + i).join('\n')}

`
    : '';

  // Generate constants section
  const constantsSection = constants.length > 0
    ? `  // ============================================================================
  // Constants
  // ============================================================================

${constants.map(c => '  ' + c).join('\n')}

`
    : '';

  // Generate the runtime.js content wrapped in async IIFE
  return `#!/usr/bin/env node
/**
 * V3 Runtime - Extracted functions for Claude Code execution
 * Generated by react-agentic
 *
 * Usage: node runtime.js <functionName> '<jsonArgs>'
 */

(async () => {
${importsSection}${constantsSection}  // ============================================================================
  // Extracted Functions
  // ============================================================================

${functionBodies.map(b => '  ' + b.split('\n').join('\n  ')).join('\n\n')}

  // ============================================================================
  // Function Registry
  // ============================================================================

  const registry = {
${functionNames.map(n => `    ${n},`).join('\n')}
  };

  // ============================================================================
  // CLI Entry Point
  // ============================================================================

  const [,, fnName, argsJson] = process.argv;

  if (!fnName) {
    console.error('Usage: node runtime.js <functionName> <jsonArgs>');
    console.error('Available functions:', Object.keys(registry).join(', '));
    process.exit(1);
  }

  const fn = registry[fnName];
  if (!fn) {
    console.error(\`Unknown function: \${fnName}\`);
    console.error('Available functions:', Object.keys(registry).join(', '));
    process.exit(1);
  }

  let args = {};
  if (argsJson) {
    try {
      args = JSON.parse(argsJson);
    } catch (e) {
      console.error(\`Invalid JSON args: \${e.message}\`);
      process.exit(1);
    }
  }

  try {
    const result = await fn(args);
    console.log(JSON.stringify(result));
  } catch (e) {
    console.error(\`Function error: \${e.message}\`);
    process.exit(1);
  }
})();
`;
}
